title : Amida Dev

safe: true
lsi: false
pygments: true
auto: true

source: amida-dev
destination: amida-dev

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://kinlane.github.io/amida-dev/

BASE_PATH : http://kinlane.github.io/amida-dev/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
